databases:
  - name: questify-db
    plan: free

services:
  - type: web
    name: questify-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    postDeployCommand: python manage.py migrate --noinput
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DJANGO_DEBUG
        value: "False"
      - key: USE_WHITENOISE
        value: "True"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: questify-db
          property: connectionString
      - key: DJANGO_ALLOWED_HOSTS
        value: '{{ env "RENDER_EXTERNAL_HOSTNAME" }}'
      - key: DJANGO_CORS_ALLOWED_ORIGINS
        sync: false
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        sync: false
      - key: OPENAI_API_KEY
        sync: false

  - type: static
    name: questify-frontend
    plan: free
    rootDir: frontend
    buildCommand: |
      npm install
      npm run build
    publishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: QUESTIFY_BACKEND_URL
        fromService:
          type: web
          name: questify-backend
          envVarKey: RENDER_EXTERNAL_URL
      - key: VITE_API_BASE_URL
        value: '{{ env "QUESTIFY_BACKEND_URL" }}/api'
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
