services:
  - type: web
    name: questify-backend
    runtime: python3
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: |
      cd backend
      gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    plan: starter
    env:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: questify-backend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: questify-db
          property: connectionString

databases:
  - name: questify-db
    databaseName: questify
    user: questify_user
    plan: starter