# Generated by Django 5.2.5 on 2025-10-19 03:41

from django.db import migrations, models


def populate_display_names(apps, schema_editor):
    UserProfile = apps.get_model('user', 'UserProfile')
    User = apps.get_model('auth', 'User')

    for profile in UserProfile.objects.select_related('user').all():
        user = profile.user
        if profile.display_name:
            continue
        name_parts = [part for part in [user.first_name, user.last_name] if part]
        full_name = " ".join(name_parts).strip()
        fallback = user.username or user.email or "User"
        name = (full_name or fallback).strip()
        profile.display_name = name
        profile.save(update_fields=['display_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_default_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.RunPython(populate_display_names, migrations.RunPython.noop),
    ]
