# Generated by Django 5.2.5 on 2025-10-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_default_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
