# Generated by Django 5.2.5 on 2025-10-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_userprofile_profile_picture_userprofile_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
