# Generated by Django 5.2.5 on 2025-09-21 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attempts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attempt",
            old_name="student",
            new_name="attempter",
        ),
    ]
