# Generated by Django 5.2.5 on 2025-09-21 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="content",
            new_name="question",
        ),
    ]
