# Generated by Django 5.2.5 on 2025-09-21 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_rename_content_question_question"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="creator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="source",
            field=models.CharField(
                choices=[("STUDENT", "Student"), ("TEACHING_TEAM", "Teaching Team")],
                default="STUDENT",
                max_length=20,
            ),
        ),
    ]
