# Generated by hand to ensure comment tables exist on legacy databases

from django.db import migrations


def ensure_comment_table(apps, schema_editor):
    Comment = apps.get_model("questions", "Comment")
    connection = schema_editor.connection
    table_names = set(connection.introspection.table_names())

    if Comment._meta.db_table in table_names:
        return

    schema_editor.create_model(Comment)


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_question_rating_count_questionrating"),
    ]

    operations = [
        migrations.RunPython(ensure_comment_table, migrations.RunPython.noop),
    ]
