# Generated by Django 5.2.5 on 2025-10-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_update_num_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='admin_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
